// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeBuy.Infrastructure.Data;

#nullable disable

namespace PrimeBuy.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306203054_AddRoles")]
    partial class AddRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role",
                            ConcurrencyStamp = "8bd9d69a-71a6-46b6-8cfc-646fd4c6bdcf",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "user-role",
                            ConcurrencyStamp = "338030d0-043a-4b20-800a-f92860ab0aa2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "u1",
                            RoleId = "admin-role"
                        },
                        new
                        {
                            UserId = "u2",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u3",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u4",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u5",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u6",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u7",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u8",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u9",
                            RoleId = "user-role"
                        },
                        new
                        {
                            UserId = "u10",
                            RoleId = "user-role"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "u1",
                            City = "New York",
                            Country = "United States",
                            IsDefault = true,
                            Street = "350 Fifth Avenue",
                            ZipCode = "10118"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "u1",
                            City = "Brooklyn",
                            Country = "United States",
                            IsDefault = false,
                            Street = "123 Atlantic Avenue",
                            ZipCode = "11201"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "u2",
                            City = "Los Angeles",
                            Country = "United States",
                            IsDefault = true,
                            Street = "6801 Hollywood Blvd",
                            ZipCode = "90028"
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = "u2",
                            City = "Santa Monica",
                            Country = "United States",
                            IsDefault = false,
                            Street = "401 Wilshire Blvd",
                            ZipCode = "90401"
                        },
                        new
                        {
                            Id = 5,
                            ApplicationUserId = "u3",
                            City = "Cairo",
                            Country = "Egypt",
                            IsDefault = true,
                            Street = "12 Tahrir Square",
                            ZipCode = "11511"
                        },
                        new
                        {
                            Id = 6,
                            ApplicationUserId = "u3",
                            City = "Alexandria",
                            Country = "Egypt",
                            IsDefault = false,
                            Street = "45 Corniche Road",
                            ZipCode = "21599"
                        },
                        new
                        {
                            Id = 7,
                            ApplicationUserId = "u4",
                            City = "Madrid",
                            Country = "Spain",
                            IsDefault = true,
                            Street = "Gran Vía 28",
                            ZipCode = "28013"
                        },
                        new
                        {
                            Id = 8,
                            ApplicationUserId = "u4",
                            City = "Barcelona",
                            Country = "Spain",
                            IsDefault = false,
                            Street = "La Rambla 91",
                            ZipCode = "08001"
                        },
                        new
                        {
                            Id = 9,
                            ApplicationUserId = "u5",
                            City = "London",
                            Country = "United Kingdom",
                            IsDefault = true,
                            Street = "221B Baker Street",
                            ZipCode = "NW16XE"
                        },
                        new
                        {
                            Id = 10,
                            ApplicationUserId = "u5",
                            City = "Manchester",
                            Country = "United Kingdom",
                            IsDefault = false,
                            Street = "10 Deansgate",
                            ZipCode = "M32BQ"
                        },
                        new
                        {
                            Id = 11,
                            ApplicationUserId = "u6",
                            City = "Chicago",
                            Country = "United States",
                            IsDefault = true,
                            Street = "875 N Michigan Avenue",
                            ZipCode = "60611"
                        },
                        new
                        {
                            Id = 12,
                            ApplicationUserId = "u6",
                            City = "Evanston",
                            Country = "United States",
                            IsDefault = false,
                            Street = "1600 Sherman Avenue",
                            ZipCode = "60201"
                        },
                        new
                        {
                            Id = 13,
                            ApplicationUserId = "u7",
                            City = "Dubai",
                            Country = "UAE",
                            IsDefault = true,
                            Street = "Sheikh Zayed Road Tower 3",
                            ZipCode = "00000"
                        },
                        new
                        {
                            Id = 14,
                            ApplicationUserId = "u7",
                            City = "Abu Dhabi",
                            Country = "UAE",
                            IsDefault = false,
                            Street = "Corniche Road West 15",
                            ZipCode = "00000"
                        },
                        new
                        {
                            Id = 15,
                            ApplicationUserId = "u8",
                            City = "Toronto",
                            Country = "Canada",
                            IsDefault = true,
                            Street = "290 Bremner Blvd",
                            ZipCode = "M5V3L9"
                        },
                        new
                        {
                            Id = 16,
                            ApplicationUserId = "u8",
                            City = "Vancouver",
                            Country = "Canada",
                            IsDefault = false,
                            Street = "1055 Canada Place",
                            ZipCode = "V6C0C3"
                        },
                        new
                        {
                            Id = 17,
                            ApplicationUserId = "u9",
                            City = "Sydney",
                            Country = "Australia",
                            IsDefault = true,
                            Street = "1 Macquarie Street",
                            ZipCode = "2000"
                        },
                        new
                        {
                            Id = 18,
                            ApplicationUserId = "u9",
                            City = "Melbourne",
                            Country = "Australia",
                            IsDefault = false,
                            Street = "100 St Kilda Road",
                            ZipCode = "3004"
                        },
                        new
                        {
                            Id = 19,
                            ApplicationUserId = "u10",
                            City = "Berlin",
                            Country = "Germany",
                            IsDefault = true,
                            Street = "Friedrichstraße 43",
                            ZipCode = "10117"
                        },
                        new
                        {
                            Id = 20,
                            ApplicationUserId = "u10",
                            City = "Munich",
                            Country = "Germany",
                            IsDefault = false,
                            Street = "Marienplatz 8",
                            ZipCode = "80331"
                        });
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u1",
                            Email = "john.doe@email.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = true,
                            MiddleName = "Michael",
                            NormalizedEmail = "JOHN.DOE@EMAIL.COM",
                            NormalizedUserName = "JOHN.DOE@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u1",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@email.com"
                        },
                        new
                        {
                            Id = "u2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u2",
                            Email = "jane.smith@email.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = true,
                            MiddleName = "Marie",
                            NormalizedEmail = "JANE.SMITH@EMAIL.COM",
                            NormalizedUserName = "JANE.SMITH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u2",
                            TwoFactorEnabled = false,
                            UserName = "jane.smith@email.com"
                        },
                        new
                        {
                            Id = "u3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u3",
                            Email = "ahmed.hassan@email.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            LastName = "Hassan",
                            LockoutEnabled = true,
                            MiddleName = "Ali",
                            NormalizedEmail = "AHMED.HASSAN@EMAIL.COM",
                            NormalizedUserName = "AHMED.HASSAN@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u3",
                            TwoFactorEnabled = false,
                            UserName = "ahmed.hassan@email.com"
                        },
                        new
                        {
                            Id = "u4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u4",
                            Email = "maria.garcia@email.com",
                            EmailConfirmed = true,
                            FirstName = "Maria",
                            LastName = "Garcia",
                            LockoutEnabled = true,
                            MiddleName = "Elena",
                            NormalizedEmail = "MARIA.GARCIA@EMAIL.COM",
                            NormalizedUserName = "MARIA.GARCIA@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u4",
                            TwoFactorEnabled = false,
                            UserName = "maria.garcia@email.com"
                        },
                        new
                        {
                            Id = "u5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u5",
                            Email = "james.wilson@email.com",
                            EmailConfirmed = true,
                            FirstName = "James",
                            LastName = "Wilson",
                            LockoutEnabled = true,
                            MiddleName = "Robert",
                            NormalizedEmail = "JAMES.WILSON@EMAIL.COM",
                            NormalizedUserName = "JAMES.WILSON@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u5",
                            TwoFactorEnabled = false,
                            UserName = "james.wilson@email.com"
                        },
                        new
                        {
                            Id = "u6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u6",
                            Email = "sara.johnson@email.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            LastName = "Johnson",
                            LockoutEnabled = true,
                            MiddleName = "Lynn",
                            NormalizedEmail = "SARA.JOHNSON@EMAIL.COM",
                            NormalizedUserName = "SARA.JOHNSON@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u6",
                            TwoFactorEnabled = false,
                            UserName = "sara.johnson@email.com"
                        },
                        new
                        {
                            Id = "u7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u7",
                            Email = "omar.khaled@email.com",
                            EmailConfirmed = true,
                            FirstName = "Omar",
                            LastName = "Ibrahim",
                            LockoutEnabled = true,
                            MiddleName = "Khaled",
                            NormalizedEmail = "OMAR.KHALED@EMAIL.COM",
                            NormalizedUserName = "OMAR.KHALED@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u7",
                            TwoFactorEnabled = false,
                            UserName = "omar.khaled@email.com"
                        },
                        new
                        {
                            Id = "u8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u8",
                            Email = "emily.brown@email.com",
                            EmailConfirmed = true,
                            FirstName = "Emily",
                            LastName = "Brown",
                            LockoutEnabled = true,
                            MiddleName = "Rose",
                            NormalizedEmail = "EMILY.BROWN@EMAIL.COM",
                            NormalizedUserName = "EMILY.BROWN@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u8",
                            TwoFactorEnabled = false,
                            UserName = "emily.brown@email.com"
                        },
                        new
                        {
                            Id = "u9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u9",
                            Email = "david.lee@email.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            LastName = "Lee",
                            LockoutEnabled = true,
                            MiddleName = "James",
                            NormalizedEmail = "DAVID.LEE@EMAIL.COM",
                            NormalizedUserName = "DAVID.LEE@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u9",
                            TwoFactorEnabled = false,
                            UserName = "david.lee@email.com"
                        },
                        new
                        {
                            Id = "u10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u10",
                            Email = "sophia.martinez@email.com",
                            EmailConfirmed = true,
                            FirstName = "Sophia",
                            LastName = "Martinez",
                            LockoutEnabled = true,
                            MiddleName = "Anne",
                            NormalizedEmail = "SOPHIA.MARTINEZ@EMAIL.COM",
                            NormalizedUserName = "SOPHIA.MARTINEZ@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELPKE2rRSojBxPzOOWBBBPczaOLosox3P4A2XNpNTCbU5hbPO3QHfbAKwXzaFTBRwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u10",
                            TwoFactorEnabled = false,
                            UserName = "sophia.martinez@email.com"
                        });
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "u1",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "u2",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "u3",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = "u4",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ApplicationUserId = "u5",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ApplicationUserId = "u6",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ApplicationUserId = "u7",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            ApplicationUserId = "u8",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            ApplicationUserId = "u9",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            ApplicationUserId = "u10",
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CartId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            CartId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            CartId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            CartId = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Name", "ParentCategoryId")
                        .IsUnique()
                        .HasFilter("[ParentCategoryId] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryImage = "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=300&h=200&fit=crop",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryImage = "https://images.unsplash.com/photo-1445205170230-053b83016050?w=300&h=200&fit=crop",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CategoryImage = "https://images.unsplash.com/photo-1556185781-a47769abb7aa?w=300&h=200&fit=crop",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CategoryImage = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=200&fit=crop",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            CategoryImage = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=200&fit=crop",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            CategoryImage = "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300&h=200&fit=crop",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 7,
                            CategoryImage = "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=300&h=200&fit=crop",
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 8,
                            CategoryImage = "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=300&h=200&fit=crop",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            CategoryImage = "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=200&fit=crop",
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 10,
                            CategoryImage = "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=300&h=200&fit=crop",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 11,
                            CategoryImage = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&h=200&fit=crop",
                            Name = "Smartphones",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryImage = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300&h=200&fit=crop",
                            Name = "Laptops",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryImage = "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=300&h=200&fit=crop",
                            Name = "Men's Clothing",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryImage = "https://images.unsplash.com/photo-1566479179817-c0cf9a5d7d1f?w=300&h=200&fit=crop",
                            Name = "Women's Clothing",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 15,
                            CategoryImage = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=200&fit=crop",
                            Name = "Cookware",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            CategoryImage = "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=200&fit=crop",
                            Name = "Fiction",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 17,
                            CategoryImage = "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300&h=200&fit=crop",
                            Name = "Running",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 18,
                            CategoryImage = "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=300&h=200&fit=crop",
                            Name = "Skincare",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 19,
                            CategoryImage = "https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=300&h=200&fit=crop",
                            Name = "Action Figures",
                            ParentCategoryId = 7
                        },
                        new
                        {
                            Id = 20,
                            CategoryImage = "https://images.unsplash.com/photo-1483653364400-eedcfb9f1f88?w=300&h=200&fit=crop",
                            Name = "Car Accessories",
                            ParentCategoryId = 8
                        });
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ApplicationUserId = "u1",
                            OrderDate = new DateTime(2026, 1, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "ABCDEFGH",
                            ShippingAddressId = 1,
                            Status = 4,
                            TotalAmount = 1369.49m
                        },
                        new
                        {
                            OrderId = 2,
                            ApplicationUserId = "u1",
                            OrderDate = new DateTime(2026, 1, 22, 9, 15, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "BCDEFGHI",
                            ShippingAddressId = 2,
                            Status = 4,
                            TotalAmount = 1234.50m
                        },
                        new
                        {
                            OrderId = 3,
                            ApplicationUserId = "u2",
                            OrderDate = new DateTime(2026, 1, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "CDEFGHIJ",
                            ShippingAddressId = 3,
                            Status = 3,
                            TotalAmount = 1549.99m
                        },
                        new
                        {
                            OrderId = 4,
                            ApplicationUserId = "u2",
                            OrderDate = new DateTime(2026, 1, 28, 11, 45, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "DEFGHIJK",
                            ShippingAddressId = 4,
                            Status = 2,
                            TotalAmount = 225.40m
                        },
                        new
                        {
                            OrderId = 5,
                            ApplicationUserId = "u3",
                            OrderDate = new DateTime(2026, 2, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "EFGHIJKL",
                            ShippingAddressId = 5,
                            Status = 4,
                            TotalAmount = 1199.00m
                        },
                        new
                        {
                            OrderId = 6,
                            ApplicationUserId = "u3",
                            OrderDate = new DateTime(2026, 2, 3, 13, 20, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "FGHIJKLM",
                            ShippingAddressId = 6,
                            Status = 3,
                            TotalAmount = 104.89m
                        },
                        new
                        {
                            OrderId = 7,
                            ApplicationUserId = "u4",
                            OrderDate = new DateTime(2026, 2, 5, 17, 10, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "GHIJKLMN",
                            ShippingAddressId = 7,
                            Status = 1,
                            TotalAmount = 379.98m
                        },
                        new
                        {
                            OrderId = 8,
                            ApplicationUserId = "u4",
                            OrderDate = new DateTime(2026, 2, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "HIJKLMNO",
                            ShippingAddressId = 8,
                            Status = 4,
                            TotalAmount = 539.98m
                        },
                        new
                        {
                            OrderId = 9,
                            ApplicationUserId = "u5",
                            OrderDate = new DateTime(2026, 2, 10, 15, 30, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "IJKLMNOP",
                            ShippingAddressId = 9,
                            Status = 2,
                            TotalAmount = 31.48m
                        },
                        new
                        {
                            OrderId = 10,
                            ApplicationUserId = "u5",
                            OrderDate = new DateTime(2026, 2, 12, 9, 45, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "JKLMNOPQ",
                            ShippingAddressId = 10,
                            Status = 3,
                            TotalAmount = 349.99m
                        },
                        new
                        {
                            OrderId = 11,
                            ApplicationUserId = "u6",
                            OrderDate = new DateTime(2026, 2, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "KLMNOPQR",
                            ShippingAddressId = 11,
                            Status = 4,
                            TotalAmount = 134.89m
                        },
                        new
                        {
                            OrderId = 12,
                            ApplicationUserId = "u6",
                            OrderDate = new DateTime(2026, 2, 15, 8, 10, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "LMNOPQRS",
                            ShippingAddressId = 12,
                            Status = 5,
                            TotalAmount = 169.99m
                        },
                        new
                        {
                            OrderId = 13,
                            ApplicationUserId = "u7",
                            OrderDate = new DateTime(2026, 2, 18, 14, 20, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "MNOPQRST",
                            ShippingAddressId = 13,
                            Status = 1,
                            TotalAmount = 1299.99m
                        },
                        new
                        {
                            OrderId = 14,
                            ApplicationUserId = "u7",
                            OrderDate = new DateTime(2026, 2, 20, 16, 30, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "NOPQRSTU",
                            ShippingAddressId = 14,
                            Status = 2,
                            TotalAmount = 59.98m
                        },
                        new
                        {
                            OrderId = 15,
                            ApplicationUserId = "u8",
                            OrderDate = new DateTime(2026, 2, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "OPQRSTUV",
                            ShippingAddressId = 15,
                            Status = 4,
                            TotalAmount = 1299.00m
                        },
                        new
                        {
                            OrderId = 16,
                            ApplicationUserId = "u8",
                            OrderDate = new DateTime(2026, 2, 24, 10, 15, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "PQRSTUVW",
                            ShippingAddressId = 16,
                            Status = 3,
                            TotalAmount = 69.98m
                        },
                        new
                        {
                            OrderId = 17,
                            ApplicationUserId = "u9",
                            OrderDate = new DateTime(2026, 2, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "QRSTUVWX",
                            ShippingAddressId = 17,
                            Status = 1,
                            TotalAmount = 190.00m
                        },
                        new
                        {
                            OrderId = 18,
                            ApplicationUserId = "u9",
                            OrderDate = new DateTime(2026, 2, 28, 13, 45, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "RSTUVWXY",
                            ShippingAddressId = 18,
                            Status = 4,
                            TotalAmount = 64.98m
                        },
                        new
                        {
                            OrderId = 19,
                            ApplicationUserId = "u10",
                            OrderDate = new DateTime(2026, 3, 1, 15, 30, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "STUVWXYZ",
                            ShippingAddressId = 19,
                            Status = 2,
                            TotalAmount = 194.98m
                        },
                        new
                        {
                            OrderId = 20,
                            ApplicationUserId = "u10",
                            OrderDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "TUVWXYZA",
                            ShippingAddressId = 20,
                            Status = 3,
                            TotalAmount = 29.99m
                        });
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 69.50m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 6,
                            Quantity = 5,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 44.90m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 1549.99m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 20,
                            Quantity = 0,
                            UnitPrice = 14.99m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 89.90m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1199.00m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            ProductId = 14,
                            Quantity = 0,
                            UnitPrice = 11.90m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 6,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 6,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 14.99m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 7,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 190.00m
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 7,
                            ProductId = 13,
                            Quantity = 0,
                            UnitPrice = 16.99m
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 8,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 349.99m
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 8,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 190.00m
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 9,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 18.99m
                        },
                        new
                        {
                            Id = 18,
                            OrderId = 9,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 12.49m
                        },
                        new
                        {
                            Id = 19,
                            OrderId = 10,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 349.99m
                        },
                        new
                        {
                            Id = 20,
                            OrderId = 10,
                            ProductId = 20,
                            Quantity = 0,
                            UnitPrice = 14.99m
                        },
                        new
                        {
                            Id = 21,
                            OrderId = 11,
                            ProductId = 13,
                            Quantity = 3,
                            UnitPrice = 16.99m
                        },
                        new
                        {
                            Id = 22,
                            OrderId = 11,
                            ProductId = 14,
                            Quantity = 3,
                            UnitPrice = 11.90m
                        },
                        new
                        {
                            Id = 23,
                            OrderId = 12,
                            ProductId = 15,
                            Quantity = 1,
                            UnitPrice = 169.99m
                        },
                        new
                        {
                            Id = 24,
                            OrderId = 12,
                            ProductId = 16,
                            Quantity = 0,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 25,
                            OrderId = 13,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1299.99m
                        },
                        new
                        {
                            Id = 26,
                            OrderId = 13,
                            ProductId = 13,
                            Quantity = 0,
                            UnitPrice = 16.99m
                        },
                        new
                        {
                            Id = 27,
                            OrderId = 14,
                            ProductId = 19,
                            Quantity = 1,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 28,
                            OrderId = 14,
                            ProductId = 16,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 29,
                            OrderId = 15,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 1299.00m
                        },
                        new
                        {
                            Id = 30,
                            OrderId = 15,
                            ProductId = 11,
                            Quantity = 0,
                            UnitPrice = 18.99m
                        },
                        new
                        {
                            Id = 31,
                            OrderId = 16,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 69.50m
                        },
                        new
                        {
                            Id = 32,
                            OrderId = 16,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            Id = 33,
                            OrderId = 17,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 190.00m
                        },
                        new
                        {
                            Id = 34,
                            OrderId = 17,
                            ProductId = 12,
                            Quantity = 0,
                            UnitPrice = 12.49m
                        },
                        new
                        {
                            Id = 35,
                            OrderId = 18,
                            ProductId = 19,
                            Quantity = 1,
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 36,
                            OrderId = 18,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 37,
                            OrderId = 19,
                            ProductId = 15,
                            Quantity = 1,
                            UnitPrice = 169.99m
                        },
                        new
                        {
                            Id = 38,
                            OrderId = 19,
                            ProductId = 16,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 39,
                            OrderId = 20,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 40,
                            OrderId = 20,
                            ProductId = 14,
                            Quantity = 0,
                            UnitPrice = 11.90m
                        });
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Samsung Galaxy S25 Ultra",
                            Price = 1299.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
                            Rating = 4.5,
                            SKU = "ELC-1001",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Apple iPhone 16 Pro",
                            Price = 1199.00m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&h=400&fit=crop",
                            Rating = 4.7999999999999998,
                            SKU = "ELC-1002",
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dell XPS 15 Laptop",
                            Price = 1549.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
                            Rating = 4.5999999999999996,
                            SKU = "ELC-2001",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "MacBook Air M4",
                            Price = 1299.00m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
                            Rating = 4.9000000000000004,
                            SKU = "ELC-2002",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Levi's 501 Original Jeans",
                            Price = 69.50m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop",
                            Rating = 4.2000000000000002,
                            SKU = "CLT-3001",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nike Dri-FIT Running Shirt",
                            Price = 35.00m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&h=400&fit=crop",
                            Rating = 4.2999999999999998,
                            SKU = "CLT-3002",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Zara Midi Satin Dress",
                            Price = 89.90m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1566479179817-c0cf9a5d7d1f?w=400&h=400&fit=crop",
                            Rating = 4.0999999999999996,
                            SKU = "CLT-4001",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Adidas Ultraboost Light",
                            Price = 190.00m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop",
                            Rating = 4.4000000000000004,
                            SKU = "SPR-5001",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Lodge Cast Iron Skillet 12\"",
                            Price = 44.90m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop",
                            Rating = 4.7000000000000002,
                            SKU = "HMK-6001",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Instant Pot Duo 7-in-1",
                            Price = 89.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1574781330855-d0db0775562a?w=400&h=400&fit=crop",
                            Rating = 4.5,
                            SKU = "HMK-6002",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Atomic Habits by James Clear",
                            Price = 18.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
                            Rating = 4.7999999999999998,
                            SKU = "BOK-7001",
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "The Great Gatsby",
                            Price = 12.49m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
                            Rating = 4.0,
                            SKU = "BOK-7002",
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CeraVe Moisturizing Cream",
                            Price = 16.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400&h=400&fit=crop",
                            Rating = 4.5999999999999996,
                            SKU = "BTY-8001",
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "The Ordinary Niacinamide Serum",
                            Price = 11.90m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
                            Rating = 4.2999999999999998,
                            SKU = "BTY-8002",
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "LEGO Star Wars Millennium Falcon",
                            Price = 169.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop",
                            Rating = 4.9000000000000004,
                            SKU = "TOY-9001",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Marvel Legends Spider-Man",
                            Price = 24.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=400&h=400&fit=crop",
                            Rating = 4.4000000000000004,
                            SKU = "TOY-9002",
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 20,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Armor All Car Cleaning Kit",
                            Price = 29.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400&h=400&fit=crop",
                            Rating = 4.2000000000000002,
                            SKU = "AUT-1101",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Garmin Forerunner 265 Watch",
                            Price = 349.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop",
                            Rating = 4.7000000000000002,
                            SKU = "SPR-5002",
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Fiskars Garden Tool Set",
                            Price = 34.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=400&fit=crop",
                            Rating = 4.0,
                            SKU = "GRD-1201",
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Vitamin D3 5000 IU Supplement",
                            Price = 14.99m,
                            ProductImageUrl = "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&h=400&fit=crop",
                            Rating = 4.0999999999999996,
                            SKU = "HLT-1301",
                            StockQuantity = 500
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimeBuy.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Address", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Addresses")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Cart", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Cart")
                        .HasForeignKey("PrimeBuy.Domain.Models.Cart", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.CartItem", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimeBuy.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Category", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Order", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PrimeBuy.Domain.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimeBuy.Domain.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Product", b =>
                {
                    b.HasOne("PrimeBuy.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PrimeBuy.Domain.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
